server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/UserProfile_db?createDatabaseIfNotExist=true
    username: root
    password: MySql@2026
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false
    
    gateway:
      url: http://172.21.232.11:8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
  override-with-generic-response: false

  #ADD THIS
  default-produces-media-type: application/json
